package com.knatware.aiworkforce.model;

import jakarta.persistence.*;
import java.time.Instant;

/**
 * An email in the system outbox. Every email — whether composed by an admin or
 * auto-generated by an event (candidate status change, interview result, meeting
 * invite) — is stored here. If SMTP is configured it is also actually sent;
 * otherwise it stays as a stored/preview record (status PENDING).
 */
@Entity
@Table(name = "email")
public class Email {
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String toAddress;
    private String fromAddress;
    private String subject;
    @Column(length = 8000)
    private String body;

    @Enumerated(EnumType.STRING)
    private EmailStatus status = EmailStatus.PENDING;

    private String trigger;     // e.g. "manual", "candidate-status", "interview-scored", "meeting-invite"
    private String error;       // populated if a real send failed
    private Instant createdAt = Instant.now();
    private Instant sentAt;

    public Email() { }

    public Email(String to, String subject, String body, String trigger) {
        this.toAddress = to; this.subject = subject; this.body = body; this.trigger = trigger;
    }

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getToAddress() { return toAddress; }
    public void setToAddress(String toAddress) { this.toAddress = toAddress; }
    public String getFromAddress() { return fromAddress; }
    public void setFromAddress(String fromAddress) { this.fromAddress = fromAddress; }
    public String getSubject() { return subject; }
    public void setSubject(String subject) { this.subject = subject; }
    public String getBody() { return body; }
    public void setBody(String body) { this.body = body; }
    public EmailStatus getStatus() { return status; }
    public void setStatus(EmailStatus status) { this.status = status; }
    public String getTrigger() { return trigger; }
    public void setTrigger(String trigger) { this.trigger = trigger; }
    public String getError() { return error; }
    public void setError(String error) { this.error = error; }
    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }
    public Instant getSentAt() { return sentAt; }
    public void setSentAt(Instant sentAt) { this.sentAt = sentAt; }

    public enum EmailStatus { PENDING, SENT, FAILED }
}
